#pragma once
/*
 * tal_asr_define.h
 *
 *  Created on: Stempber 14, 2020
 *      Author: yanzikui
 */
namespace TAL_ASR {
enum TAL_ASR_STAT_CODE {
  TAL_ASR_OK = 0,
  TAL_ASR_ERROR = -1,
  TAL_ASR_CONFIG_FILE_NOT_FOUND = -101,
  TAL_ASR_CONFIG_VERSION_NOT_FOUND = -102,
  TAL_ASR_CONFIG_MODEL_NOT_FOUND = -103,
  TAL_ASR_CONFIG_DICT_NOT_FOUND = -104,
  TAL_ASR_CONFIG_VADCFG_NOT_FOUND = -105,
  TAL_ASR_CONFIG_MODEL_LOAD_ERROR = -106,
  TAL_ASR_CONFIG_BPE_LOAD_ERROR = -107,
  TAL_ASR_CONFIG_WORDDICT_LOAD_ERROR = -108,
  TAL_ASR_CONFIG_VADPARAMS_LOAD_ERROR = -109,
};

enum TAL_LANGUAGE {
  TAL_UNKNOWN = 0,
  TAL_MANDARIN = 1,          // 中文普通话
  TAL_ENGLISH = 2,           // 英文
  TAL_MANDARIN_ENGLISH = 3,  // 中英混合
};

enum TAL_RECOGNIZE {
  TAL_RECOGNIZE_ERROR = -1,
  TAL_RECOGNIZE_OK = 0,
  TAL_RECOGNIZE_HAS_RESULT = 1,
  TAL_RECOGNIZE_FINAL_RESULT = 2,
};
}  // namespace TAL_ASR
